apiVersion: v1
kind: Service
metadata:
  name: kafka
  labels:
    app.kubernetes.io/name: kafka
    app.kubernetes.io/component: local-development-infrastructure
    traceforge.dev/infrastructure: local-development
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/name: kafka
  ports:
    - name: broker
      port: 19092
      targetPort: broker
