apiVersion: v1
kind: ServiceAccount
metadata:
  name: ingest-gateway
  namespace: traceforge
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/part-of: traceforge
    traceforge.dev/environment: kind-local
    traceforge.dev/foundation: local-kind
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kafka
  namespace: traceforge
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/part-of: traceforge
    traceforge.dev/environment: kind-local
    traceforge.dev/foundation: local-kind
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: traceforge-worker
  namespace: traceforge
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/part-of: traceforge
    traceforge.dev/environment: kind-local
    traceforge.dev/foundation: local-kind
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: traceforge-api
  namespace: traceforge
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/part-of: traceforge
    traceforge.dev/environment: kind-local
    traceforge.dev/foundation: local-kind
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: otel-collector
  namespace: traceforge
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/part-of: traceforge
    traceforge.dev/environment: kind-local
    traceforge.dev/foundation: local-kind
automountServiceAccountToken: false
