apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
labels:
  - pairs:
      traceforge.dev/environment: kind-local
    includeSelectors: false
patches:
  - path: persistent-volume-claim.yaml
