"""Deterministic pytest export for approved replay specifications."""

from __future__ import annotations

import os
from pathlib import Path

from traceforge.exceptions import TraceForgeError


class ExportError(TraceForgeError):
    """A regression test cannot be exported safely."""


def export_pytest(
    capsule: Path,
    runner: str,
    spec: Path,
    output: Path,
    *,
    force: bool = False,
) -> None:
    """Write a readable test that retains references to its source artifacts."""
    if output.exists() and not force:
        raise ExportError(f"output already exists: {output}; use --force to replace it")
    capsule_ref = Path(os.path.relpath(capsule.resolve(), output.parent.resolve())).as_posix()
    spec_ref = Path(os.path.relpath(spec.resolve(), output.parent.resolve())).as_posix()
    source = f'''"""Generated by TraceForge from developer-approved replay artifacts."""

import json
from pathlib import Path

from traceforge import load_runner, replay_exact


def test_traceforge_regression() -> None:
    base = Path(__file__).resolve().parent
    capsule = json.loads((base / {capsule_ref!r}).read_text(encoding="utf-8"))
    spec = json.loads((base / {spec_ref!r}).read_text(encoding="utf-8"))
    result = replay_exact(capsule, load_runner({runner!r}), spec)
    assert result.regression is not None
    assert result.regression.passed, result.regression.to_dict()
'''
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(source, encoding="utf-8")
