"""Deterministic pytest export for approved replay specifications."""

from __future__ import annotations

import io
import json
import os
import zipfile
from pathlib import Path
from typing import Any

from traceforge.exceptions import TraceForgeError


class ExportError(TraceForgeError):
    """A regression test cannot be exported safely."""


_BUNDLE_ENTRIES = (
    "replay-capsule.json",
    "regression-spec.json",
    "test_traceforge_regression.py",
)


def render_pytest(capsule_reference: str, runner: str, spec_reference: str) -> str:
    """Render the deterministic pytest source shared by file and browser export."""
    return f'''"""Generated by TraceForge from developer-approved replay artifacts."""

import json
from pathlib import Path

from traceforge import load_runner, replay_exact


def test_traceforge_regression() -> None:
    base = Path(__file__).resolve().parent
    capsule = json.loads((base / {capsule_reference!r}).read_text(encoding="utf-8"))
    spec = json.loads((base / {spec_reference!r}).read_text(encoding="utf-8"))
    result = replay_exact(capsule, load_runner({runner!r}), spec)
    assert result.regression is not None
    assert result.regression.passed, result.regression.to_dict()
'''


def _json_bytes(value: Any) -> bytes:
    try:
        source = json.dumps(
            value,
            allow_nan=False,
            ensure_ascii=False,
            indent=2,
            sort_keys=True,
        )
    except (TypeError, ValueError) as exc:
        raise ExportError(f"regression bundle value is not strict JSON: {exc}") from exc
    return f"{source}\n".encode()


def render_regression_bundle(capsule: Any, spec: Any, runner: str) -> bytes:
    """Return one deterministic, path-safe ZIP containing a coherent regression set."""
    contents = (
        _json_bytes(capsule),
        _json_bytes(spec),
        render_pytest(_BUNDLE_ENTRIES[0], runner, _BUNDLE_ENTRIES[1]).encode(),
    )
    target = io.BytesIO()
    with zipfile.ZipFile(target, "w", compression=zipfile.ZIP_STORED) as archive:
        for name, content in zip(_BUNDLE_ENTRIES, contents, strict=True):
            entry = zipfile.ZipInfo(name, date_time=(1980, 1, 1, 0, 0, 0))
            entry.compress_type = zipfile.ZIP_STORED
            entry.create_system = 3
            entry.external_attr = 0o100644 << 16
            archive.writestr(entry, content)
    return target.getvalue()


def export_pytest(
    capsule: Path,
    runner: str,
    spec: Path,
    output: Path,
    *,
    force: bool = False,
) -> None:
    """Write a readable test that retains references to its source artifacts."""
    if output.exists() and not force:
        raise ExportError(f"output already exists: {output}; use --force to replace it")
    capsule_ref = Path(os.path.relpath(capsule.resolve(), output.parent.resolve())).as_posix()
    spec_ref = Path(os.path.relpath(spec.resolve(), output.parent.resolve())).as_posix()
    source = render_pytest(capsule_ref, runner, spec_ref)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(source, encoding="utf-8")
